apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend/deploy.yml
- frontend/deploy.yml
- backend/service.yml
- frontend/service.yml


images:
- name: 858431073453.dkr.ecr.us-east-1.amazonaws.com/workshop-devops/prod/backend
  newName: 858431073453.dkr.ecr.us-east-1.amazonaws.com/workshop-devops/prod/backend
  newTag: 851c0069ecad50d19f697afd7332f510e844f35d
- name: 858431073453.dkr.ecr.us-east-1.amazonaws.com/workshop-devops/prod/frontend
  newName: 858431073453.dkr.ecr.us-east-1.amazonaws.com/workshop-devops/prod/frontend
  newTag: v1
